const CFG={SUPABASE_URL:"",SUPABASE_ANON_KEY:""};
const LANG={English:{},Kannada:{"Home":"ಮುಖಪುಟ","Services":"ಸೇವೆಗಳು","Projects":"ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು","Calendar":"ಕ್ಯಾಲೆಂಡರ್","Teams":"ತಂಡಗಳು","Contact":"ಸಂಪರ್ಕ","Start a Project":"ಪ್ರಾಜೆಕ್ಟ್ ಆರಂಭಿಸಿ","Every Idea Has a Story, We Make It Real":"ಪ್ರತಿ ಆಲೋಚನೆಗೂ ಒಂದು ಕಥೆ ಇದೆ, ನಾವು ಅದನ್ನು ನಿಜಗೊಳಿಸುತ್ತೇವೆ"},Hindi:{"Home":"होम","Services":"सेवाएँ","Projects":"प्रोजेक्ट्स","Calendar":"कैलेंडर","Teams":"टीम","Contact":"संपर्क","Start a Project":"प्रोजेक्ट शुरू करें"},Telugu:{"Home":"హోమ్","Services":"సేవలు","Projects":"ప్రాజెక్టులు","Calendar":"క్యాలెండర్","Teams":"టీమ్","Contact":"సంప్రదించండి"},Tamil:{"Home":"முகப்பு","Services":"சேவைகள்","Projects":"திட்டங்கள்","Calendar":"காலண்டர்","Teams":"குழு","Contact":"தொடர்பு"},Malayalam:{"Home":"ഹോം","Services":"സേവനങ്ങൾ","Projects":"പ്രോജക്ടുകൾ","Calendar":"കലണ്ടർ","Teams":"ടീം","Contact":"ബന്ധപ്പെടുക"},Marathi:{"Home":"मुख्यपृष्ठ","Services":"सेवा","Projects":"प्रकल्प","Calendar":"कॅलेंडर","Teams":"संघ","Contact":"संपर्क"},Bengali:{"Home":"হোম","Services":"সেবা","Projects":"প্রকল্প","Calendar":"ক্যালেন্ডার","Teams":"টিম","Contact":"যোগাযোগ"},Gujarati:{"Home":"હોમ","Services":"સેવાઓ","Projects":"પ્રોજેક્ટ્સ","Calendar":"કૅલેન્ડર","Teams":"ટીમ","Contact":"સંપર્ક"},Punjabi:{"Home":"ਹੋਮ","Services":"ਸੇਵਾਵਾਂ","Projects":"ਪ੍ਰੋਜੈਕਟ","Calendar":"ਕੈਲੰਡਰ","Teams":"ਟੀਮ","Contact":"ਸੰਪਰਕ"},Urdu:{"Home":"ہوم","Services":"خدمات","Projects":"پروجیکٹس","Calendar":"کیلنڈر","Teams":"ٹیم","Contact":"رابطہ"}};
const pageNames=['Home','Services','Work','Start Project','Pricing','Projects Overview','Calendar','Enquiries','Team 1','Team 2','Payments','Transactions','Reports','Reviews','Portfolio','About Us','Blog','FAQs','Contact Us','AI Assistant'];
function role(){return localStorage.getItem('3fs-role')||'Owner'}
function setRole(r){localStorage.setItem('3fs-role',r);location.reload()}
function canEdit(){return role()==='Owner'||role()==='Team Member'}
function setup(){
 document.querySelectorAll('[data-role]').forEach(x=>x.textContent=role());
 document.querySelectorAll('[data-edit]').forEach(x=>{x.disabled=!canEdit();x.title=canEdit()?'Editable for owner/team member':'Client view is read-only'});
 const sel=document.querySelector('#language'); if(sel){sel.value=localStorage.getItem('3fs-lang')||'English';sel.onchange=()=>{localStorage.setItem('3fs-lang',sel.value);applyLang(sel.value)}}
 const rs=document.querySelector('#roleSelect');if(rs){rs.value=role();rs.onchange=()=>setRole(rs.value)}
 const status=document.querySelector('#dbStatus');if(status){status.textContent=(CFG.SUPABASE_URL&&CFG.SUPABASE_ANON_KEY)?'⚡ Supabase Connected':'○ Local Demo / Add Supabase keys';status.className='pill '+((CFG.SUPABASE_URL&&CFG.SUPABASE_ANON_KEY)?'connected':'')}
 applyLang(localStorage.getItem('3fs-lang')||'English');
}
function applyLang(l){const d=LANG[l]||{};document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;if(d[k])e.textContent=d[k]})}
function toggleChat(){document.querySelector('.chatbox')?.classList.toggle('open')}
function sendChat(){const i=document.querySelector('#chatInput');if(!i||!i.value.trim())return;const m=document.querySelector('#messages');const text=i.value.trim();m.insertAdjacentHTML('beforeend',`<div class="msg me">${esc(text)}</div>`);let ans='I can help with 3FS services, pricing, project status, enquiries, payments, calendar and portfolio.';const q=text.toLowerCase();if(q.includes('price'))ans='3FS sample plans: Basic ₹4,999 • Standard ₹9,999 • Advanced ₹14,999. Final price can be edited by the owner/team.';else if(q.includes('team'))ans='Team 1: Dhanush, Amulya, Aditya, Ranjitha. Team 2: Gagan, Tejas, Koushik, Chinmayee, Geetha.';else if(q.includes('project'))ans='Use Start Project to submit an enquiry. Team members can update status; clients can only view their status.';else if(q.includes('payment'))ans='Payments and Transactions are shown separately. Transaction records are read-only for clients.';m.insertAdjacentHTML('beforeend',`<div class="msg bot">${ans}</div>`);m.scrollTop=m.scrollHeight;i.value=''}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function saveField(k,v){if(!canEdit())return alert('Client view is read-only. Only Owner and Team Member can edit.');localStorage.setItem('3fs-'+k,v);alert('Saved locally. With Supabase configured, sync can be enabled.')}
document.addEventListener('DOMContentLoaded',setup);