(function(){
const LANG={
 en:{start:'Start a Project',services:'Services',portfolio:'Portfolio',about:'About Us',reviews:'Reviews',contact:'Contact',language:'Language',chat:'3FS AI Assistant',calendar:'Calendar',save:'Save',send:'Send'},
 kn:{start:'ಪ್ರಾಜೆಕ್ಟ್ ಪ್ರಾರಂಭಿಸಿ',services:'ಸೇವೆಗಳು',portfolio:'ಪೋರ್ಟ್‌ಫೋಲಿಯೊ',about:'ನಮ್ಮ ಬಗ್ಗೆ',reviews:'ವಿಮರ್ಶೆಗಳು',contact:'ಸಂಪರ್ಕ',language:'ಭಾಷೆ',chat:'3FS AI ಸಹಾಯಕ',calendar:'ಕ್ಯಾಲೆಂಡರ್',save:'ಉಳಿಸಿ',send:'ಕಳುಹಿಸಿ'},
 hi:{start:'प्रोजेक्ट शुरू करें',services:'सेवाएँ',portfolio:'पोर्टफोलियो',about:'हमारे बारे में',reviews:'समीक्षाएँ',contact:'संपर्क',language:'भाषा',chat:'3FS AI सहायक',calendar:'कैलेंडर',save:'सहेजें',send:'भेजें'},
 te:{start:'ప్రాజెక్ట్ ప్రారంభించండి',services:'సేవలు',portfolio:'పోర్ట్‌ఫోలియో',about:'మా గురించి',reviews:'సమీక్షలు',contact:'సంప్రదించండి',language:'భాష',chat:'3FS AI సహాయకుడు',calendar:'క్యాలెండర్',save:'సేవ్',send:'పంపండి'},
 ta:{start:'திட்டத்தை தொடங்குங்கள்',services:'சேவைகள்',portfolio:'போர்ட்ஃபோலியோ',about:'எங்களை பற்றி',reviews:'விமர்சனங்கள்',contact:'தொடர்பு',language:'மொழி',chat:'3FS AI உதவியாளர்',calendar:'காலண்டர்',save:'சேமி',send:'அனுப்பு'},
 ml:{start:'പ്രോജക്റ്റ് ആരംഭിക്കുക',services:'സേവനങ്ങൾ',portfolio:'പോർട്ട്ഫോളിയോ',about:'ഞങ്ങളേക്കുറിച്ച്',reviews:'അവലോകനങ്ങൾ',contact:'ബന്ധപ്പെടുക',language:'ഭാഷ',chat:'3FS AI സഹായി',calendar:'കലണ്ടർ',save:'സംരക്ഷിക്കുക',send:'അയയ്ക്കുക'},
 mr:{start:'प्रकल्प सुरू करा',services:'सेवा',portfolio:'पोर्टफोलिओ',about:'आमच्याबद्दल',reviews:'अभिप्राय',contact:'संपर्क',language:'भाषा',chat:'3FS AI सहाय्यक',calendar:'कॅलेंडर',save:'जतन करा',send:'पाठवा'},
 bn:{start:'প্রজেক্ট শুরু করুন',services:'সেবা',portfolio:'পোর্টফোলিও',about:'আমাদের সম্পর্কে',reviews:'রিভিউ',contact:'যোগাযোগ',language:'ভাষা',chat:'3FS AI সহায়ক',calendar:'ক্যালেন্ডার',save:'সংরক্ষণ',send:'পাঠান'},
 gu:{start:'પ્રોજેક્ટ શરૂ કરો',services:'સેવાઓ',portfolio:'પોર્ટફોલિયો',about:'અમારા વિશે',reviews:'સમીક્ષાઓ',contact:'સંપર્ક',language:'ભાષા',chat:'3FS AI સહાયક',calendar:'કૅલેન્ડર',save:'સાચવો',send:'મોકલો'},
 pa:{start:'ਪ੍ਰੋਜੈਕਟ ਸ਼ੁਰੂ ਕਰੋ',services:'ਸੇਵਾਵਾਂ',portfolio:'ਪੋਰਟਫੋਲੀਓ',about:'ਸਾਡੇ ਬਾਰੇ',reviews:'ਸਮੀਖਿਆਵਾਂ',contact:'ਸੰਪਰਕ',language:'ਭਾਸ਼ਾ',chat:'3FS AI ਸਹਾਇਕ',calendar:'ਕੈਲੰਡਰ',save:'ਸੇਵ',send:'ਭੇਜੋ'},
 od:{start:'ପ୍ରୋଜେକ୍ଟ ଆରମ୍ଭ କରନ୍ତୁ',services:'ସେବା',portfolio:'ପୋର୍ଟଫୋଲିଓ',about:'ଆମ ବିଷୟରେ',reviews:'ସମୀକ୍ଷା',contact:'ଯୋଗାଯୋଗ',language:'ଭାଷା',chat:'3FS AI ସହାୟକ',calendar:'କ୍ୟାଲେଣ୍ଡର',save:'ସଞ୍ଚୟ',send:'ପଠାନ୍ତୁ'},
 ur:{start:'پروجیکٹ شروع کریں',services:'خدمات',portfolio:'پورٹ فولیو',about:'ہمارے بارے میں',reviews:'جائزے',contact:'رابطہ',language:'زبان',chat:'3FS AI معاون',calendar:'کیلنڈر',save:'محفوظ کریں',send:'بھیجیں'}
};
window.setLanguage=function(lang){localStorage.setItem('3fs_lang',lang);const d=LANG[lang]||LANG.en;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.getAttribute('data-i18n');if(d[k])el.textContent=d[k]});const sel=document.getElementById('lang3fs');if(sel)sel.value=lang;};
window.saveEnquiry=async function(e){e.preventDefault();const item=Object.fromEntries(new FormData(e.target).entries());item.createdAt=new Date().toISOString();if(window.threefsDB)await threefsDB.add('enquiries',item);const old=JSON.parse(localStorage.getItem('3fs_enquiries')||'[]');old.push(item);localStorage.setItem('3fs_enquiries',JSON.stringify(old));const msg=document.getElementById('formMsg');if(msg)msg.textContent=threefsDB?.status()||'Saved';e.target.reset();};
window.demoPay=async function(){const item={project:document.getElementById('payProject')?.textContent||'Project',amount:document.getElementById('payAmount')?.textContent||'',method:document.getElementById('method')?.value||'',status:'Demo recorded'};if(window.threefsDB)await threefsDB.add('payments',item);const msg=document.getElementById('payMsg');if(msg)msg.textContent='Payment transaction recorded for the team website. Demo mode: no real money was charged.';renderTransactions();};
window.teamLogin=function(){const code=prompt('3FS Team Edit Code (trial):');if(code==='3FS-TEAM-EDIT'){document.getElementById('editbox')?.classList.add('show')}else if(code!==null)alert('Team edit access denied.');};
window.saveTeam=async function(){for(let i=0;i<9;i++){const n=(document.getElementById('en'+i)||{}).value?.trim()||'Team Member',r=(document.getElementById('er'+i)||{}).value?.trim()||'Team Member',s=(document.getElementById('es'+i)||{}).value?.trim()||'Creative Services';[['name',n],['role',r],['service',s]].forEach(([k,v])=>{const el=document.getElementById(k+i);if(el)el.textContent=v});}const team=[];for(let i=0;i<9;i++)team.push({name:document.getElementById('name'+i)?.textContent||'',role:document.getElementById('role'+i)?.textContent||'',service:document.getElementById('service'+i)?.textContent||'',team:i<4?'Team 1':'Team 2'});localStorage.setItem('3fs_team',JSON.stringify(team));if(window.threefsDB)for(const m of team)await threefsDB.add('team',m);alert('Team 1 and Team 2 details saved. Clients cannot edit.');};
function esc(x){return String(x).replace(/[<>&]/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[m]))}
function injectTools(){if(document.getElementById('threefs-tools'))return;const box=document.createElement('div');box.id='threefs-tools';box.innerHTML=`<div class="lang-switcher"><label data-i18n="language">Language</label><select id="lang3fs"><option value="en">English</option><option value="kn">ಕನ್ನಡ</option><option value="hi">हिन्दी</option><option value="te">తెలుగు</option><option value="ta">தமிழ்</option><option value="ml">മലയാളം</option><option value="mr">मराठी</option><option value="bn">বাংলা</option><option value="gu">ગુજરાતી</option><option value="pa">ਪੰਜਾਬੀ</option><option value="od">ଓଡ଼ିଆ</option><option value="ur">اردو</option></select></div><button class="ai-fab" id="aiFab" aria-label="Open 3FS AI Assistant">✦</button><div class="ai-chat" id="aiChat"><div class="ai-head"><b data-i18n="chat">3FS AI Assistant</b><button id="aiClose">×</button></div><div class="ai-body" id="aiBody"><div class="ai-msg bot">Hi! I am the 3FS website assistant. Ask me about our services, pricing, enquiries, dates, payments, teams, portfolio or client status.</div></div><div class="ai-quick"><button data-q="services">Services</button><button data-q="pricing">Pricing</button><button data-q="project">Start a project</button><button data-q="calendar">Calendar</button><button data-q="payment">Payments</button><button data-q="team">Teams</button></div><div class="ai-input"><input id="aiInput" placeholder="Ask about 3FS work..."><button id="aiSend">Send</button></div></div>`;document.body.appendChild(box);const sel=document.getElementById('lang3fs');sel.value=localStorage.getItem('3fs_lang')||'en';sel.onchange=()=>setLanguage(sel.value);const chat=document.getElementById('aiChat'),body=document.getElementById('aiBody');document.getElementById('aiFab').onclick=()=>chat.classList.toggle('show');document.getElementById('aiClose').onclick=()=>chat.classList.remove('show');
function answer(q){q=q.toLowerCase();if(/price|plan|cost|₹/.test(q))return'3FS basic plans start around ₹4,999 and standard around ₹9,999. Final pricing depends on scope and the enquiry.';if(/service|what do you/.test(q))return'3FS offers graphic design, UI/UX, web development, video editing, digital marketing and content creation.';if(/calendar|date|schedule|meeting/.test(q))return'Use the Calendar page to choose a date. Selected dates are stored for the team calendar when the database bridge is configured.';if(/payment|transaction|receipt/.test(q))return'Payments and transaction records are available in the payment flow. Demo transactions are stored for the team record.';if(/team|member/.test(q))return'Team 1: Dhanush, Amulya, Aditya, Ranjitha. Team 2: Gagan, Tejas, Koushik, Chinmayee, Geetha. Only authorised team members can edit.';if(/project|enquir/.test(q))return'Use Start a Project, enter your details, choose a service and preferred date, then submit. The enquiry is stored in the website record system.';return'I am the 3FS-specific AI Assistant. I can help with 3FS services, pricing, projects, calendar, payments, teams, portfolio, enquiries and client status.'}
function send(text){if(!text.trim())return;body.insertAdjacentHTML('beforeend',`<div class="ai-msg user">${esc(text)}</div><div class="ai-msg bot">${esc(answer(text))}</div>`);body.scrollTop=body.scrollHeight}document.getElementById('aiSend').onclick=()=>{const i=document.getElementById('aiInput');send(i.value);i.value=''};document.getElementById('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('aiSend').click()});document.querySelectorAll('.ai-quick button').forEach(b=>b.onclick=()=>send(b.textContent));}
function renderCalendar(){const el=document.getElementById('3fsCalendar');if(!el)return;const now=new Date(),y=now.getFullYear(),m=now.getMonth();const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();const names=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];let h='<div class="cal-head">'+names.map(x=>`<b>${x}</b>`).join('')+'</div><div class="cal-grid">';for(let i=0;i<first;i++)h+='<span></span>';for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;h+=`<button type="button" data-date="${date}">${d}</button>`}h+='</div>';el.innerHTML=h;el.querySelectorAll('button').forEach(b=>b.onclick=async()=>{const date=b.dataset.date;el.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const label=document.getElementById('selectedDate');if(label)label.textContent=date;if(window.threefsDB)await threefsDB.add('calendar',{date,type:'client-selected'});const st=document.getElementById('dbStatus');if(st)st.textContent=window.threefsDB?.status()||'Saved';});}
function renderTransactions(){const body=document.getElementById('transactionRows');if(!body||!window.threefsDB)return;const rows=threefsDB.all('payments');if(!rows.length){body.innerHTML='<tr><td colspan="5">No transactions recorded yet.</td></tr>';return}body.innerHTML=rows.slice().reverse().map(x=>`<tr><td>${esc(new Date(x.createdAt||Date.now()).toLocaleString())}</td><td>${esc(x.project)}</td><td>${esc(x.amount)}</td><td>${esc(x.method)}</td><td><span class="status done">${esc(x.status||'Recorded')}</span></td></tr>`).join('')}
document.addEventListener('DOMContentLoaded',()=>{injectTools();setLanguage(localStorage.getItem('3fs_lang')||'en');renderCalendar();renderTransactions();const st=document.getElementById('dbStatus');if(st&&window.threefsDB)st.textContent=window.threefsDB.status();});
})();
